#!/usr/bin/env bash
# How to install the new webserver on nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
sudo sh -c 'echo "Hello World" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
