#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but prints Hi at 9
n=0
while ((n < 10))
do
	((n++))
	if [ $n -eq 4 ]
	then
		echo "bad luck"
	elif [ $n -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
